language: node_js
cache: npm
stages:
  - check
  - test
  - cov

node_js:
  - '12'
  - '13'

os:
  - linux
  - osx
  - windows

script: npx nyc -s npm run test:node -- --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      script:
        - npx aegir commitlint --travis
        - npm run depcheck
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script: npm run test:browser

    - stage: test
      name: chrome webworker
      addons:
        chrome: stable
      script: npm run test:webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npm run test:browser -- --browsers FirefoxHeadless

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npm run test:webworker -- --browsers FirefoxHeadless

notifications:
  email: false
